import { WebSocket } from "ws";

export interface ServerProcess {
  id: string;
  status: "starting" | "running" | "stopping" | "stopped" | "crashed";
  startedAt?: Date;
  stoppedAt?: Date;
  logs: string[];
  memoryUsed: number;
  cpuPercent: number;
  networkRx: number;
  networkTx: number;
  playerCount: number;
  clients: Set<WebSocket>;
  intervals: NodeJS.Timeout[];
}

export interface FileEntry {
  name: string;
  path: string;
  isDir: boolean;
  content?: string;
  size: number;
  updatedAt: string;
}

const processes = new Map<string, ServerProcess>();
const fileSystems = new Map<string, Map<string, FileEntry>>();

function defaultFiles(serverType: string): FileEntry[] {
  const now = new Date().toISOString();
  const isPlugin = ["paper", "spigot", "bungeecord"].includes(serverType);
  const isMod = ["forge", "fabric"].includes(serverType);

  const files: FileEntry[] = [
    { name: "server.properties", path: "/server.properties", isDir: false, size: 1247, updatedAt: now, content: `#Minecraft server properties\n#Generated by VortexPanel\nenable-jmx-monitoring=false\nrcon.port=25575\nlevel-seed=\ngamemode=survival\nenable-command-block=false\nenable-query=false\ngenerator-settings={}\nlevel-name=world\nmotd=A Minecraft Server\nquery.port=25565\npvp=true\ndifficulty=easy\nnetwork-compression-threshold=256\nrequire-resource-pack=false\nmax-tick-time=60000\nuse-native-transport=true\nmax-players=20\nonline-mode=true\nenable-status=true\nallow-flight=false\nbroadcast-rcon-to-ops=true\nview-distance=10\nserver-ip=\nresource-pack-prompt=\nallow-nether=true\nserver-port=25565\nenable-rcon=false\nsync-chunk-writes=true\nop-permission-level=4\nprevent-proxy-connections=false\nhide-online-players=false\nresource-pack=\nentity-broadcast-range-percentage=100\nsimulation-distance=10\nrcon.password=\nplayer-idle-timeout=0\ndebug=false\nforce-gamemode=false\nrate-limit=0\nhardcore=false\nwhite-list=false\nbroadcast-console-to-ops=true\nspawn-npcs=true\nspawn-animals=true\nfunction-permission-level=2\ninitial-enabled-packs=vanilla\nlevel-type=minecraft\\:normal\nspawn-monsters=true\nenforce-whitelist=false\nspawn-protection=16\nmax-world-size=29999984` },
    { name: "eula.txt", path: "/eula.txt", isDir: false, size: 149, updatedAt: now, content: `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).\n#${now}\neula=true` },
    { name: "ops.json", path: "/ops.json", isDir: false, size: 130, updatedAt: now, content: `[\n  {\n    "uuid": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",\n    "name": "AdminPlayer",\n    "level": 4,\n    "bypassesPlayerLimit": false\n  }\n]` },
    { name: "whitelist.json", path: "/whitelist.json", isDir: false, size: 72, updatedAt: now, content: `[\n  {\n    "uuid": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",\n    "name": "AdminPlayer"\n  }\n]` },
    { name: "banned-players.json", path: "/banned-players.json", isDir: false, size: 4, updatedAt: now, content: "[]" },
    { name: "banned-ips.json", path: "/banned-ips.json", isDir: false, size: 4, updatedAt: now, content: "[]" },
    { name: "usercache.json", path: "/usercache.json", isDir: false, size: 112, updatedAt: now, content: "[]" },
    { name: "server.log", path: "/server.log", isDir: false, size: 4096, updatedAt: now, content: "[INFO] Starting minecraft server version 1.21.1\n[INFO] Loading properties\n[INFO] Default game type: SURVIVAL\n[INFO] Generating keypair\n[INFO] Starting Minecraft server on *:25565\n[INFO] Done (2.347s)! For help, type \"help\"" },
    { name: "world", path: "/world", isDir: true, size: 0, updatedAt: now },
    { name: "world_nether", path: "/world_nether", isDir: true, size: 0, updatedAt: now },
    { name: "world_the_end", path: "/world_the_end", isDir: true, size: 0, updatedAt: now },
    { name: "crash-reports", path: "/crash-reports", isDir: true, size: 0, updatedAt: now },
  ];

  if (isPlugin) {
    files.push({ name: "plugins", path: "/plugins", isDir: true, size: 0, updatedAt: now });
    files.push({
      name: "paper.yml", path: "/paper.yml", isDir: false, size: 512, updatedAt: now,
      content: `# Paper configuration file\nmax-auto-save-chunks-per-tick: 24\noptimize-explosions: false\nspawn-limits:\n  monsters: 70\n  animals: 10\n  water-animals: 15\n  water-ambient: 20\nunknown-commands-silent: false\nmessages:\n  kick:\n    authentication-servers-down: ''\n    connection-throttle: Connection throttled! Please wait before reconnecting.\n    flying-player: Flying is not enabled on this server\n    flying-vehicle: Flying is not enabled on this server\n`
    });
    files.push({
      name: "spigot.yml", path: "/spigot.yml", isDir: false, size: 512, updatedAt: now,
      content: `# Spigot configuration file\nsettings:\n  debug: false\n  bungeecord: false\n  sample-count: 12\n  player-shuffle: 0\n  user-cache-size: 1000\nmessages:\n  whitelist: You are not whitelisted on this server!\n  unknown-command: Unknown command. Type \"/help\" for help.\n  server-full: The server is full!\n  outdated-client: 'Outdated client! Please use {0}'\n  outdated-server: Outdated server! I''m still on {0}\n`
    });
  }

  if (isMod) {
    files.push({ name: "mods", path: "/mods", isDir: true, size: 0, updatedAt: now });
    files.push({ name: "config", path: "/config", isDir: true, size: 0, updatedAt: now });
    files.push({
      name: "forge-server.toml", path: "/forge-server.toml", isDir: false, size: 256, updatedAt: now,
      content: `# Forge server configuration\n[server]\n  # Forge client-side only mods setting\n  loadClientSideMods = false\n  # Recap installed mods on login\n  modListRecap = true\n  # Maximum player count\n  maxPlayers = 20\n`
    });
  }

  return files;
}

export function initFileSystem(serverId: string, serverType = "paper"): void {
  if (!fileSystems.has(serverId)) {
    const fs = new Map<string, FileEntry>();
    for (const f of defaultFiles(serverType)) {
      fs.set(f.path, f);
    }
    fileSystems.set(serverId, fs);
  }
}

export function listFiles(serverId: string, dirPath = "/"): FileEntry[] {
  const fs = fileSystems.get(serverId);
  if (!fs) return [];

  const entries: FileEntry[] = [];
  const normalizedDir = dirPath.endsWith("/") && dirPath !== "/" ? dirPath.slice(0, -1) : dirPath;

  for (const [path, entry] of fs.entries()) {
    if (path === normalizedDir) continue;
    const withoutDir = path.startsWith(normalizedDir === "/" ? "" : normalizedDir)
      ? path.substring(normalizedDir === "/" ? 0 : normalizedDir.length)
      : null;
    if (!withoutDir) continue;
    const parts = withoutDir.replace(/^\//, "").split("/");
    if (parts.length === 1 && normalizedDir === "/") {
      entries.push(entry);
    } else if (parts.length === 1 && normalizedDir !== "/") {
      entries.push(entry);
    } else if (parts.length === 2 && normalizedDir !== "/" && parts[0] === "") {
      entries.push(entry);
    }
  }

  return entries.sort((a, b) => {
    if (a.isDir !== b.isDir) return a.isDir ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
}

export function readFile(serverId: string, filePath: string): FileEntry | null {
  const fs = fileSystems.get(serverId);
  if (!fs) return null;
  return fs.get(filePath) ?? null;
}

export function writeFile(serverId: string, filePath: string, content: string): FileEntry {
  let fs = fileSystems.get(serverId);
  if (!fs) {
    fs = new Map();
    fileSystems.set(serverId, fs);
  }

  const name = filePath.split("/").filter(Boolean).pop() ?? filePath;
  const entry: FileEntry = {
    name,
    path: filePath,
    isDir: false,
    content,
    size: Buffer.byteLength(content, "utf8"),
    updatedAt: new Date().toISOString(),
  };
  fs.set(filePath, entry);
  return entry;
}

export function deleteFilePath(serverId: string, filePath: string): boolean {
  const fs = fileSystems.get(serverId);
  if (!fs) return false;

  const entry = fs.get(filePath);
  if (!entry) return false;

  fs.delete(filePath);

  if (entry.isDir) {
    const prefix = filePath.endsWith("/") ? filePath : filePath + "/";
    for (const path of Array.from(fs.keys())) {
      if (path.startsWith(prefix)) {
        fs.delete(path);
      }
    }
  }

  return true;
}

export function createDirectory(serverId: string, dirPath: string): FileEntry {
  let fs = fileSystems.get(serverId);
  if (!fs) {
    fs = new Map();
    fileSystems.set(serverId, fs);
  }
  const name = dirPath.split("/").filter(Boolean).pop() ?? dirPath;
  const entry: FileEntry = {
    name,
    path: dirPath,
    isDir: true,
    size: 0,
    updatedAt: new Date().toISOString(),
  };
  fs.set(dirPath, entry);
  return entry;
}

export function createFile(serverId: string, filePath: string): FileEntry | "exists" {
  let fs = fileSystems.get(serverId);
  if (!fs) {
    fs = new Map();
    fileSystems.set(serverId, fs);
  }
  if (fs.has(filePath)) return "exists";
  const name = filePath.split("/").filter(Boolean).pop() ?? filePath;
  const entry: FileEntry = {
    name,
    path: filePath,
    isDir: false,
    content: "",
    size: 0,
    updatedAt: new Date().toISOString(),
  };
  fs.set(filePath, entry);
  return entry;
}

export function renameFilePath(serverId: string, oldPath: string, newName: string): FileEntry | "exists" | null {
  const fs = fileSystems.get(serverId);
  if (!fs) return null;

  const entry = fs.get(oldPath);
  if (!entry) return null;

  const parentDir = oldPath.substring(0, oldPath.lastIndexOf("/")) || "/";
  const newPath = parentDir === "/" ? `/${newName}` : `${parentDir}/${newName}`;

  if (newPath !== oldPath) {
    if (fs.has(newPath)) return "exists";

    const updatedEntry: FileEntry = {
      ...entry,
      name: newName,
      path: newPath,
      updatedAt: new Date().toISOString(),
    };
    fs.delete(oldPath);
    fs.set(newPath, updatedEntry);

    if (entry.isDir) {
      for (const [path, child] of Array.from(fs.entries())) {
        if (path.startsWith(oldPath + "/")) {
          const newChildPath = newPath + path.substring(oldPath.length);
          const updatedChild: FileEntry = { ...child, path: newChildPath, updatedAt: new Date().toISOString() };
          fs.delete(path);
          fs.set(newChildPath, updatedChild);
        }
      }
    }

    return updatedEntry;
  }

  return entry;
}

export function moveFilePath(serverId: string, sourcePath: string, destPath: string): FileEntry | "same" | "subtree" | "exists" | null {
  const fs = fileSystems.get(serverId);
  if (!fs) return null;

  const entry = fs.get(sourcePath);
  if (!entry) return null;

  if (sourcePath === destPath) return "same";

  const sourcePrefix = sourcePath.endsWith("/") ? sourcePath : sourcePath + "/";
  if (entry.isDir && destPath.startsWith(sourcePrefix)) return "subtree";

  if (fs.has(destPath)) return "exists";

  const childrenToMove = entry.isDir
    ? Array.from(fs.entries()).filter(([path]) => path.startsWith(sourcePrefix))
    : [];

  fs.delete(sourcePath);
  for (const [path] of childrenToMove) fs.delete(path);

  const now = new Date().toISOString();
  const updatedEntry: FileEntry = {
    ...entry,
    name: destPath.split("/").filter(Boolean).pop() ?? entry.name,
    path: destPath,
    updatedAt: now,
  };
  fs.set(destPath, updatedEntry);

  for (const [path, child] of childrenToMove) {
    const newChildPath = destPath + path.substring(sourcePath.length);
    fs.set(newChildPath, { ...child, path: newChildPath, updatedAt: now });
  }

  return updatedEntry;
}

export function copyFilePath(serverId: string, sourcePath: string, destPath: string): FileEntry | "same" | "subtree" | "exists" | null {
  const fs = fileSystems.get(serverId);
  if (!fs) return null;

  const entry = fs.get(sourcePath);
  if (!entry) return null;

  if (sourcePath === destPath) return "same";

  const sourcePrefix = sourcePath.endsWith("/") ? sourcePath : sourcePath + "/";
  if (entry.isDir && destPath.startsWith(sourcePrefix)) return "subtree";

  if (fs.has(destPath)) return "exists";

  const childrenToCopy = entry.isDir
    ? Array.from(fs.entries()).filter(([path]) => path.startsWith(sourcePrefix))
    : [];

  const now = new Date().toISOString();
  const name = destPath.split("/").filter(Boolean).pop() ?? entry.name;
  const copiedEntry: FileEntry = { ...entry, name, path: destPath, updatedAt: now };
  fs.set(destPath, copiedEntry);

  for (const [path, child] of childrenToCopy) {
    const newChildPath = destPath + path.substring(sourcePath.length);
    fs.set(newChildPath, { ...child, path: newChildPath, updatedAt: now });
  }

  return copiedEntry;
}

export function compressPath(serverId: string, sourcePath: string, destZipPath: string): FileEntry | "exists" | null {
  const fs = fileSystems.get(serverId);
  if (!fs) return null;

  const entry = fs.get(sourcePath);
  if (!entry) return null;

  if (fs.has(destZipPath)) return "exists";

  const now = new Date().toISOString();
  const name = destZipPath.split("/").filter(Boolean).pop() ?? "archive.zip";
  const zipEntry: FileEntry = {
    name,
    path: destZipPath,
    isDir: false,
    size: Math.max(entry.size, 1024),
    content: undefined,
    updatedAt: now,
  };
  fs.set(destZipPath, zipEntry);
  return zipEntry;
}

export function extractZip(serverId: string, zipPath: string, destDirPath: string): FileEntry | "exists" | null {
  const fs = fileSystems.get(serverId);
  if (!fs) return null;

  const zipEntry = fs.get(zipPath);
  if (!zipEntry || zipEntry.isDir) return null;

  if (fs.has(destDirPath)) return "exists";

  const now = new Date().toISOString();
  const dirName = destDirPath.split("/").filter(Boolean).pop() ?? "extracted";
  const dirEntry: FileEntry = {
    name: dirName,
    path: destDirPath,
    isDir: true,
    size: 0,
    updatedAt: now,
  };
  fs.set(destDirPath, dirEntry);

  const placeholder: FileEntry = {
    name: "extracted-files.txt",
    path: `${destDirPath}/extracted-files.txt`,
    isDir: false,
    content: `# Extracted from ${zipEntry.name}\n# Extraction simulated by VortexPanel\n`,
    size: 60,
    updatedAt: now,
  };
  fs.set(placeholder.path, placeholder);

  return dirEntry;
}

export function initServer(id: string): void {
  if (!processes.has(id)) {
    processes.set(id, {
      id,
      status: "stopped",
      logs: [],
      memoryUsed: 0,
      cpuPercent: 0,
      networkRx: 0,
      networkTx: 0,
      playerCount: 0,
      clients: new Set(),
      intervals: [],
    });
  }
}

export function getProcess(id: string): ServerProcess | undefined {
  return processes.get(id);
}

function broadcast(proc: ServerProcess, message: string): void {
  proc.logs.push(message);
  if (proc.logs.length > 500) proc.logs.shift();

  for (const client of proc.clients) {
    if (client.readyState === WebSocket.OPEN) {
      client.send(message);
    }
  }
}

const startupMessages = [
  "[Server thread/INFO]: Starting minecraft server version 1.21.1",
  "[Server thread/INFO]: Loading properties",
  "[Server thread/INFO]: Default game type: SURVIVAL",
  "[Server thread/INFO]: Generating keypair",
  "[Server thread/INFO]: Starting Minecraft server on *:25565",
  "[Server thread/INFO]: Using epoll channel type",
  "[Server thread/INFO]: Preparing level \"world\"",
  "[Server thread/INFO]: Preparing start region for dimension minecraft:overworld",
  "[Server thread/INFO]: Preparing spawn area: 0%",
  "[Server thread/INFO]: Preparing spawn area: 33%",
  "[Server thread/INFO]: Preparing spawn area: 66%",
  "[Server thread/INFO]: Preparing spawn area: 100%",
  "[Server thread/INFO]: Time elapsed: 3124 ms",
  "[Server thread/INFO]: Done (3.124s)! For help, type \"help\"",
];

export async function startServer(id: string, memoryMb: number): Promise<void> {
  const proc = processes.get(id);
  if (!proc || proc.status === "running") return;

  proc.status = "starting";
  proc.startedAt = new Date();
  proc.memoryUsed = 0;
  proc.cpuPercent = 0;

  let msgIdx = 0;
  const startupInterval = setInterval(() => {
    if (msgIdx < startupMessages.length) {
      broadcast(proc, startupMessages[msgIdx]);
      msgIdx++;
    } else {
      clearInterval(startupInterval);
      proc.status = "running";
      proc.memoryUsed = Math.floor(memoryMb * 0.45);
      proc.cpuPercent = 5 + Math.random() * 10;
      proc.playerCount = 0;

      const statsInterval = setInterval(() => {
        if (proc.status !== "running") { clearInterval(statsInterval); return; }
        proc.cpuPercent = Math.max(2, Math.min(95, proc.cpuPercent + (Math.random() * 10 - 5)));
        proc.memoryUsed = Math.max(
          Math.floor(memoryMb * 0.3),
          Math.min(Math.floor(memoryMb * 0.85), proc.memoryUsed + Math.floor(Math.random() * 20 - 8))
        );
        proc.networkRx += Math.floor(Math.random() * 5000);
        proc.networkTx += Math.floor(Math.random() * 2000);
      }, 3000);

      const heartbeatInterval = setInterval(() => {
        if (proc.status !== "running") { clearInterval(heartbeatInterval); return; }
        const msgs = [
          "[Server thread/INFO]: Saving the game (this may cause the game to stop for a moment!)",
          "[Server thread/INFO]: Saved the game",
          `[Server thread/INFO]: There are ${proc.playerCount} of a max of 20 players online`,
          "[Server thread/INFO]: [VortexPanel] Heartbeat OK",
        ];
        broadcast(proc, msgs[Math.floor(Math.random() * msgs.length)]);
      }, 30000);

      proc.intervals.push(statsInterval, heartbeatInterval);
    }
  }, 600);

  proc.intervals.push(startupInterval);
}

export async function stopServer(id: string): Promise<void> {
  const proc = processes.get(id);
  if (!proc || proc.status === "stopped") return;

  proc.status = "stopping";
  const msgs = [
    "[Server thread/INFO]: Stopping the server",
    "[Server thread/INFO]: Stopping server",
    "[Server thread/INFO]: Saving players",
    "[Server thread/INFO]: Saving worlds",
    "[Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld",
    "[Server thread/INFO]: ThreadedAnvilChunkStorage: All chunks are saved",
    "[Server thread/INFO]: Flushing profiler...",
  ];

  let i = 0;
  const stopInterval = setInterval(() => {
    if (i < msgs.length) {
      broadcast(proc, msgs[i]);
      i++;
    } else {
      clearInterval(stopInterval);
      for (const iv of proc.intervals) clearInterval(iv);
      proc.intervals = [];
      proc.status = "stopped";
      proc.stoppedAt = new Date();
      proc.memoryUsed = 0;
      proc.cpuPercent = 0;
      proc.playerCount = 0;
    }
  }, 400);

  proc.intervals.push(stopInterval);
}

export async function restartServer(id: string, memoryMb: number): Promise<void> {
  await stopServer(id);
  setTimeout(() => startServer(id, memoryMb), 3000);
}

export async function killServer(id: string): Promise<void> {
  const proc = processes.get(id);
  if (!proc) return;
  for (const iv of proc.intervals) clearInterval(iv);
  proc.intervals = [];
  proc.status = "stopped";
  proc.stoppedAt = new Date();
  proc.memoryUsed = 0;
  proc.cpuPercent = 0;
  proc.playerCount = 0;
  broadcast(proc, "[Server thread/INFO]: Server killed by operator");
}

export async function sendCommand(id: string, command: string): Promise<void> {
  const proc = processes.get(id);
  if (!proc) return;

  broadcast(proc, `> ${command}`);

  if (proc.status !== "running") {
    broadcast(proc, "[ERROR]: Server is not running");
    return;
  }

  const cmd = command.trim().toLowerCase();
  if (cmd === "help") {
    broadcast(proc, "[Server thread/INFO]: --- Showing help page 1 of 12 ---");
    broadcast(proc, "[Server thread/INFO]: /ban <player> [reason]");
    broadcast(proc, "[Server thread/INFO]: /gamemode <mode> [player]");
    broadcast(proc, "[Server thread/INFO]: /give <player> <item> [amount]");
    broadcast(proc, "[Server thread/INFO]: /list -- Shows list of online players");
    broadcast(proc, "[Server thread/INFO]: /op <player> -- Grants op status");
    broadcast(proc, "[Server thread/INFO]: /stop -- Stops the server");
    broadcast(proc, "[Server thread/INFO]: /tp <player1> <player2> -- Teleport");
    broadcast(proc, "[Server thread/INFO]: /whitelist <add|remove|list|on|off|reload>");
  } else if (cmd === "list") {
    broadcast(proc, `[Server thread/INFO]: There are ${proc.playerCount} of a max of 20 players online: ${proc.playerCount > 0 ? "Player1" : ""}`);
  } else if (cmd === "stop") {
    setTimeout(() => stopServer(id), 500);
  } else if (cmd.startsWith("say ")) {
    broadcast(proc, `[Server thread/INFO]: [Server] ${command.substring(4)}`);
  } else if (cmd.startsWith("op ")) {
    broadcast(proc, `[Server thread/INFO]: Opped ${command.substring(3).trim()}`);
  } else if (cmd.startsWith("ban ")) {
    broadcast(proc, `[Server thread/INFO]: Banned player ${command.substring(4).trim().split(" ")[0]}`);
  } else if (cmd === "whitelist list") {
    broadcast(proc, "[Server thread/INFO]: There are 1 whitelisted players: AdminPlayer");
  } else if (cmd === "whitelist on") {
    broadcast(proc, "[Server thread/INFO]: Whitelist is now turned on");
  } else if (cmd === "whitelist off") {
    broadcast(proc, "[Server thread/INFO]: Whitelist is now turned off");
  } else if (cmd === "save-all") {
    broadcast(proc, "[Server thread/INFO]: Saving...");
    setTimeout(() => broadcast(proc, "[Server thread/INFO]: Saved the game"), 800);
  } else if (cmd === "tps") {
    const tps = (18 + Math.random() * 2).toFixed(2);
    broadcast(proc, `[Server thread/INFO]: TPS from last 1m, 5m, 15m: ${tps}, ${tps}, ${tps}`);
  } else if (cmd === "version") {
    broadcast(proc, "[Server thread/INFO]: This server is running Paper version 1.21.1-DEV (MC: 1.21.1)");
  } else if (cmd === "plugins" || cmd === "pl") {
    broadcast(proc, "[Server thread/INFO]: Plugins (3): EssentialsX, WorldGuard, LuckPerms");
  } else {
    broadcast(proc, `[Server thread/WARN]: Unknown or incomplete command, see 'help'`);
  }
}

export function getLogs(id: string, lines = 100): string[] {
  const proc = processes.get(id);
  if (!proc) return [];
  return proc.logs.slice(-lines);
}

export function addClient(id: string, ws: WebSocket): void {
  const proc = processes.get(id);
  if (!proc) return;
  proc.clients.add(ws);
}

export function removeClient(id: string, ws: WebSocket): void {
  const proc = processes.get(id);
  if (!proc) return;
  proc.clients.delete(ws);
}

export function getStats(id: string, diskMb: number, memoryMb: number) {
  const proc = processes.get(id);
  const running = proc?.status === "running";
  return {
    serverId: id,
    cpuPercent: running ? proc!.cpuPercent : 0,
    memoryUsed: running ? proc!.memoryUsed : 0,
    memoryLimit: memoryMb,
    diskUsed: Math.floor(diskMb * 0.38),
    diskLimit: diskMb,
    networkRx: proc?.networkRx ?? 0,
    networkTx: proc?.networkTx ?? 0,
    uptime: running && proc!.startedAt ? Math.floor((Date.now() - proc!.startedAt.getTime()) / 1000) : 0,
    playerCount: proc?.playerCount ?? 0,
  };
}
